name: NeoClassic
favicon: null
layout_spectrum: 0.8448
typography_spectrum: 0.23947
title: 'Neo Classical Fusion '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#7a94ad'
    - '#a7b7c8'
    - '#dce3e9'
    - '#506982'
  brandStrength: 0.5
  lightness: 0.9290572730824351
  saturation: 0.7109888743143529
  rhythmicContrast: 0.25
purpose: []
