typography_spectrum: 0.33781
color:
  brandColors:
    - '#ff0100'
    - '#feff00'
    - '#ff8000'
    - '#6b6b6b'
    - '#4a0000'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.7109888743143529
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.64657
analytics:
  google: null
  facebook: null
  twitter: null
name: NeoClassic
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: 'Neo Classical Fusion '
description: Explorations in complex music
purpose: []
