name: NeoClassic
favicon: null
layout_spectrum: 0.8448
typography_spectrum: 0.31898
title: 'Neo Classical Fusion '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#786756'
    - '#514539'
    - '#2e2013'
    - '#f1c996'
    - '#914921'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.7109888743143529
  rhythmicContrast: 0.5
purpose: []
