name: NeoClassic
favicon: null
layout_spectrum: 0.8448
typography_spectrum: 0.31898
title: 'Neo Classical Fusion '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f3f3'
    - '#e54e0b'
    - '#9b1408'
    - '#db802f'
    - '#f6c07b'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.7109888743143529
  rhythmicContrast: 0.5
purpose: []
